shops_kill-bk/blog/urls.py
from django.conf.urls import *
from . import views

app_name = 'market'  #必须要加声明所用的命名空间
urlpatterns=[
    url(r'^$',views.index),
    url(r'^detail/(?P<sid>[0-9]*)$', views.detail, name='detail'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_ajax/$', views.login_ajax, name='login_ajax'),
    url(r'^verify_code/[1-9]*$', views.verify_code, name='verify_code'),
    url(r'^regiter/$', views.regiter, name='regiter'),
    url(r'^regiter_ajax/$', views.regiter_ajax, name='regiter_ajax'),
    url(r'^kill_ajax/$', views.kill_ajax, name='kill_ajax'),
    url(r'^person/$', views.person, name='person'),
    url(r'^data_edit/$', views.data_edit, name='data_edit'),
    url(r'^password_edit/$', views.password_edit, name='password_edit'),
    url(r'^order_list/$', views.order_list, name='order_list'),
    url(r'^points_list/$', views.points_list, name='points_list'),
    url(r'^exit_ajax/$', views.exit_ajax, name='exit_ajax'),
    url(r'^edit_pass_ajax/$', views.edit_pass_ajax, name='edit_pass_ajax'),
    url(r'^edit_data_ajax/$', views.edit_data_ajax, name='edit_data_ajax'),
]

shops_kill-bk/myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import *
from django.views.static import  serve
from .settings import *


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^upload/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url('index/',include('blog.urls',namespace='market')),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^static/(?P<path>.*)$',serve,{'document_root': STATIC_ROOT}),
]

shops_kill-bk/blog/models.py
from django.db import models
from DjangoUeditor.models import UEditorField
from django import forms
from django.core.exceptions import ValidationError
from django.contrib import admin, messages
import hashlib
#from DjangoUeditor.widgets import UEditorWidget
#from DjangoUeditor.forms import  UEditorField,UEditorModelForm
#import django.utils.timezone as timezone

class Shops(models.Model):
    name = models.CharField(max_length=255,null=True, verbose_name="名称" )
    price = models.DecimalField(null=True, max_digits=16, decimal_places=2, verbose_name="价格")
    oldprice = models.DecimalField(null=True, max_digits=16, decimal_places=2, verbose_name='原价')
    stock = models.IntegerField(null=True, verbose_name="库存")
    sales = models.IntegerField(null=True, verbose_name='销量')
    pic = models.ImageField(upload_to='img', null=True, verbose_name="形象图")
    starttime = models.DateTimeField(editable=True, verbose_name="抢购开始时间", null=True)
    endtime = models.DateTimeField(editable=True, verbose_name="抢购结束时间", null=True)
    # 使发布时间显示在列中
    addtime = models.DateTimeField(editable=True, auto_now_add=True, verbose_name="发布时间", null=True)
    text = UEditorField('详情',width=600, height=300, toolbars="full", imagePath="upload/ueditor/img/", filePath="upload/ueditor/img/", upload_settings={"imageMaxSize":1204000},
             settings={},command=None,event_handler='',blank=True,null=True)

    class Meta:   #中文表名
        verbose_name = '商品列表'
        # 末尾不加s
        verbose_name_plural = '商品列表'
    def __str__(self):
      return self.name


class Shop_users(models.Model):
    name = models.CharField(max_length=255, null=True, verbose_name="用户名")
    password = models.CharField(max_length=255, null=True, verbose_name="密码", editable=False)  # 后台不可修改
    score = models.FloatField(default=5000, verbose_name='用户积分')   # 初始积分5000
    phone = models.CharField(max_length=255, null=True, verbose_name='联系电话')
    adress = models.CharField(max_length=255, null=True, verbose_name='收货地址')
    #readonly_fields = ('image_data',)  # 必须加这行 否则访问编辑页面会报错
    addtime = models.DateTimeField(auto_now_add=True, verbose_name="注册时间",null=True,editable=True)

    class Meta:   #中文表名
        verbose_name = '商城用户'
        # 末尾不加s
        verbose_name_plural = '商城用户'

    # def save(self, force_insert=False, force_update=False, using=None,   #定制save事件，商城用户不可通过后台新增修改
    #          update_fields=None):
    #     return

    def __str__(self):
        return self.name


#  订单表
class Orders(models.Model):
    orderid = models.CharField(max_length=50, null=False, verbose_name="订单号")
    shopid = models.IntegerField(null=False, verbose_name="商品id", editable=False)
    uid = models.IntegerField(null=False, verbose_name="用户id", editable=False)  # 后台不可修改
    shopname = models.CharField(max_length=255, null=True, verbose_name='商品名称')
    uname = models.CharField(max_length=255, null=True, verbose_name='用户名')
    adress = models.CharField(max_length=255, null=True, verbose_name='收货地址')
    state = models.CharField(max_length=255, null=True, verbose_name='订单状态')  # 未支付，已支付，已发货
    # readonly_fields = ('image_data',)  # 必须加这行 否则访问编辑页面会报错
    addtime = models.DateTimeField(verbose_name="订单生成时间", null=False)
    paymoney = models.DecimalField(null=True, max_digits=16, decimal_places=2, verbose_name='支付价格')
    class Meta:  # 中文表名
        verbose_name = '订单列表'
        # 末尾不加s
        verbose_name_plural = '订单列表'

    # def save(self, force_insert=False, force_update=False, using=None,  # 定制save事件，订单不可通过后台新增修改
    #          update_fields=None):
    #     return

    def __str__(self):
        return self.orderid

shops_kill-bk/blog/views.py
from django.shortcuts import render
from django.http import *
from . import models
from django.forms.models import model_to_dict
import time
import datetime
import json
from PIL import Image, ImageDraw, ImageFont
import random
from io import BytesIO
import hashlib
from django.db import transaction
from django.http import HttpResponseRedirect

#  商品列表页面
def index(request):
    shops = models.Shops.objects.all()
    for vo in shops:
        vo.percent = int( float(vo.sales) / float(vo.stock) * 100)  # 计算销量百分比，销量/库存

    return render(request, 'blog/index.html', {'shops':shops})

#  商品秒杀页面
def detail(request,sid):
    data = models.Shops.objects.get(id=sid)
    now_time = int(time.time())  #当前时间
    start_time = int(time.mktime(data.starttime.timetuple()))  #datetime转时间戳格式,秒杀开始时间
    end_time = int(time.mktime(data.endtime.timetuple()))  #秒杀结束时间

    return render(request, 'blog/detail.html',{
        'data':data,
        'start_time':json.dumps(start_time), # 传参到js中处理
        'end_time':json.dumps(end_time)
    })


#  注册页面
def regiter(request):
    return render(request, 'blog/regiter.html')


#  登录页面
def login(request):
    return render(request, 'blog/login.html')

#个人中心页面
def person(request):
    uid = request.session.get('uid')
    if not uid:
        return HttpResponseRedirect('/index/login')  #未登录跳转登录页
    list = models.Shop_users.objects.get(id = uid)
    list.addtime = list.addtime.strftime( '%Y-%m-%d' )
    return render(request,'blog/person.html',{'list':list})

#资料修改页面
def data_edit(request):
    uid = request.session.get('uid')  # 用户id
    try:
        Uinfo = models.Shop_users.objects.get( id = uid)
        return render(request, 'blog/data_edit.html',{'Uinfo':Uinfo})
    except:
        return render(request, 'blog/data_edit.html')


#密码修改页面
def password_edit(request):
    return render(request,'blog/password_edit.html')

#订单列表页面
def order_list(request):
    uid = request.session.get('uid')
    if not uid:
        return HttpResponseRedirect('/index/login')  # 检查是否登录,未登录跳转登录页
    print(uid)

    list = models.Orders.objects.filter(uid = uid)  #查询订单表，单签用户下的订单
    if list:
        for x in list:
            shopinfo = models.Shops.objects.filter(id = x.shopid)
            x.img = shopinfo[0].pic
            x.addtime = x.addtime.strftime( '%Y-%m-%d %H:%M:%S' )
    return render(request, 'blog/order_list.html', {'list':list})
    # except:
    #     return render(request, 'blog/order_list.html',{'list':[]})


#积分列表页面
def points_list(request):
    uid = request.session.get('uid')
    score_list = models.Orders.objects.filter(uid = uid)
    Uinfo = models.Shop_users.objects.filter(id = uid)
    Uscore = Uinfo[0].score
    for x in score_list:
        x.addtime = x.addtime.strftime('%Y-%m-%d %H:%M:%S')
    return render(request,'blog/points_list.html',{'score_list':score_list, 'Uscore':Uscore})


#修改地址动作
def edit_data_ajax(request):
    if request.is_ajax():  # 验证是否ajax请求,防止爬虫
        uid = request.session.get('uid')  # 用户id
        phone = request.POST.get('phone')  # 电话
        adress = request.POST.get('adress')  # 地址
        try:
            Uinfo = models.Shop_users.objects.get(id=uid)
            Uinfo.phone = phone
            Uinfo.adress = adress
            Uinfo.save()
            return JsonResponse({'res': '1', 'msg': '修改成功'})
        except:
            return JsonResponse({'res': '-1', 'msg': '啊欧，出错了，请重试'})
    else:
        return JsonResponse({'res': '-1', 'msg': '非法请求'})

#修改密码动作
def edit_pass_ajax(request):
    if request.is_ajax():  #验证是否ajax请求
        uid = request.session.get('uid') #用户id
        password = request.POST.get('password')  # 密码
        oldpassword = request.POST.get('oldpassword')  # 原密码
        print(1222222)
        md5 = hashlib.md5()
        md5_2 = hashlib.md5()
        md5.update(password.encode(encoding='utf-8')) #将原密码进行MD5加密与数据库比对
        password = md5.hexdigest()
        oldpassword = md5_2.update(oldpassword.encode(encoding='utf-8'))
        oldpassword = md5_2.hexdigest()
        print(password)
        print(oldpassword)
        # return
        try:
            Uinfo = models.Shop_users.objects.get(id = uid)
            if Uinfo.password == oldpassword:
                Uinfo.password = password
                Uinfo.save()
                return JsonResponse({'res': '1', 'msg': '修改成功'})
            else:
                return JsonResponse({'res': '-1', 'msg': '原密码错误'})
        except:
            return JsonResponse({'res': '-1', 'msg': '啊欧，出错了，请重试'})
    else:
        return JsonResponse({'res': '-1', 'msg': '非法请求'})


#退出登录动作
def exit_ajax(request):
    if request.is_ajax():  # 验证是否ajax请求
        islogin = request.session.get('isLogin')
        if not islogin:
            return JsonResponse({'res': '-1', 'msg': '尚未登录'})
        else:
            request.session.clear()  # 删除session
            return JsonResponse({'res': '1', 'msg': '退出成功'})
        # except:
        #     return JsonResponse({'res': '-1', 'msg': '操作失败请重试'})
    else:
        return JsonResponse({'res': '-1', 'msg': '非法请求'})

 #  登录验证
def login_ajax(request):
    md5 = hashlib.md5()
    if request.is_ajax():  #验证是否ajax请求
        uname = request.POST.get('uname') #用户名
        password = request.POST.get('password')  # 密码
        md5.update(password.encode(encoding='utf-8'))  # ( 数据库中密码采用md5(sha1()) 加密方法)
        password = md5.hexdigest()
        vcode = request.POST.get('vcode') #提交的验证码
        vcode_session = request.session.get('verifycode') #session中的验证码
        try:
            Uinfo = models.Shop_users.objects.get(name = uname)
        except:
            return JsonResponse({'res': '-1', 'msg': '用户名不存在'})

        #用户名和密码校验
        if password == Uinfo.password and vcode.upper() == vcode_session.upper(): #将验证码同时转为大写比较，即不区分大小写
            # 保存用户的登录状态
            request.session['isLogin'] = True
            request.session['uname'] = uname
            request.session['uid'] = Uinfo.id
            return JsonResponse({'res':'1', 'msg': '登录成功'})
        elif password != Uinfo.password:
            return JsonResponse({'res':'-1', 'msg': '密码错误'})
        elif vcode.upper() != vcode_session.upper():
            return JsonResponse({'res':'-1', 'msg': '验证码错误'})


    else:
        return JsonResponse({'res': '-1', 'msg': '非法请求'})

#   注册动作
def regiter_ajax(request):
    if request.is_ajax():
        uname = request.POST.get('uname')  # 用户名
        password = request.POST.get('password')  # 密码
        adress = request.POST.get('adress')  # 收货地址
        phone = request.POST.get('phone')  # 收货地址
        vcode = request.POST.get('vcode')  # 提交的验证码
        try:
            Uinfo = models.Shop_users.objects.get(name=uname) # 查询数据库用户名是否存在，不存在则抛出异常
            print(Uinfo.score)
            return JsonResponse({'res': '-1', 'msg': '用户名已被注册，换个用户名试试吧'})
        except:
            pass

        vcode_session = request.session.get('verifycode')  # session中的验证码
        if vcode.upper() != vcode_session.upper():  # 将验证码同时转为大写比较，即不区分大小写
            return JsonResponse({'res': '-1', 'msg': '图形验证码错误'})
        if uname.strip() == '' or password.strip() == '' or adress.strip() == '':  # 验证用户名，密码，地址是否为空
            return JsonResponse({'res': '-1', 'msg': '必要参数缺失'})
        # if Uinfo :

        print(password.encode(encoding='utf-8'))
        addtime = datetime.datetime.now()
        md5 = hashlib.md5()
        md5.update(password.encode(encoding='utf-8'))  # 对密码进行MD5加密(前端已进行sha1加密，因此最终密码是双重加密)
        # print(md5)
        password = md5.hexdigest()
        dic = {'name':uname, 'password':password, 'adress':adress, 'addtime':addtime, 'phone':phone}
        # print(dic)
        # return
        try:
            models.Shop_users.objects.create(**dic)
            return JsonResponse({'res': '1', 'msg': '注册成功'})
        except:
            return JsonResponse({'res': '-1', 'msg': '注册失败，请重试'})

    return JsonResponse({'res': '-1', 'msg': '非法请求'})


#  秒杀动作
def kill_ajax(request):
    if request.is_ajax():
        isLogin = request.session.get('isLogin')  # 获取登录信息，判断是否登录
        sid = request.POST.get('sid')  # 商品id

        print(isLogin)
        if not isLogin :
            return JsonResponse({'res': '-2', 'msg': '检测到未登录，是否跳转登录页面'})
        if not sid :
            return JsonResponse({'res': '-1', 'msg': '缺少必要参数'})

        # 启用事务。如果产生了异常，就会回滚这次事务
        shiwu = transaction.savepoint()
        try:
            Uid =  request.session.get('uid')
            print(Uid)
            Shopinfo = models.Shops.objects.get(id = sid)
            Uinfo = models.Shop_users.objects.get(id = Uid)
            start_time = int(time.mktime(Shopinfo.starttime.timetuple()))  # datetime转时间戳格式,秒杀开始时间
            end_time = int(time.mktime(Shopinfo.endtime.timetuple()))  # 秒杀结束时间
            ux_now = time.time()  # 当前时间戳
            m_now = int(ux_now)  # 当前时间戳（秒级，用于转换日期格式）
            hm_now = str(int(ux_now * 1000))[-3:]  # 当前时间戳（毫秒级截取后三位，即当前的毫秒）

            if start_time > ux_now :  # 判断秒杀是否开始
                transaction.savepoint_rollback(shiwu)
                return JsonResponse({'res': '-1', 'msg': '咦？活动还没开始，怎么提交的呢'})
            elif end_time < ux_now:  # 判断秒杀活动是否结束
                transaction.savepoint_rollback(shiwu)
                return JsonResponse({'res': '-1', 'msg': '啊欧，慢了一步，活动已经结束了'})
            elif Shopinfo.stock < 1 :   # 判断库存是否为0
                transaction.savepoint_rollback(shiwu)
                return JsonResponse({'res': '-1', 'msg': '被抢购完了'})
            elif Uinfo.score < Shopinfo.price :  # 判断用户余额是否足够
                transaction.savepoint_rollback(shiwu)
                return JsonResponse({'res': '-1', 'msg': '积分余额不足'})
            else:
                print('kkk')
                Shopinfo.stock -= 1
                Shopinfo.sales += 1
                Shopinfo.save()
                print(Uinfo.score)
                print(Shopinfo.price)
                Uinfo.score = float(Uinfo.score) - float(Shopinfo.price)   #计算用户余额
                Uinfo.save()
                print('ppppp')

shops_kill-bk/blog/templates/blog/data_edit.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>编辑地址</title>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/mall.css' %}" type="text/css" />
    <link combofile="/fd/h5/wx/seckill/index.shtml" rel="stylesheet" href="{% static 'css/index.min_f89eeb50.css' %}" onerror="__reloadResource(this)">

    <script src="{% static 'layui/layui.all.js' %}"></script>
</head>
<body>
<div class="mall_main">
<div id="child_header">
    <div class="goback"><a href="javascript:history.back(-1)"><i></i></a></div>
    <div class="current_location"><span>编辑地址</span></div>
    <div class="next_operate"><a href="javascript:;" onclick="edit_data_ajax()"><span>保存</span></a></div>
</div>
<div class="address_edit">
    {% csrf_token %}
    <ul>
        <li>
            <span>联系电话</span><input type="text" value="{{ Uinfo.phone }}" id="phone">
        </li>
        <!--<li>-->
         <!--<form name="form2" method="post" action="">-->
          <!--<p class="gender">-->
           <!--<label>-->
            <!--<input type="radio" name="gender" value="man" id="gender_2">-->
            <!--先生</label>-->
           <!--<label>-->
            <!--<input type="radio" name="gender" value="woman" id="gender_3">-->
            <!--女士</label>-->
           <!--<br>-->
          <!--</p>-->
         <!--</form>-->
        <!--</li>-->
        <!--<li><span>手机号码</span><input name="tel" type="text" value="18921120000" maxlength="11"></li>-->
        <!--<li><span>所在地区</span>-->
            <!--<div id="area_adr" class="area_adr">-->
            <!--<div class="m_zlxg" id="shengfen">-->
                <!--<p title="">选择省份</p>-->
                <!--<div class="m_zlxg2">-->
                    <!--<ul></ul>-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="m_zlxg" id="chengshi">-->
                <!--<p title="">选择城市</p>-->
                <!--<div class="m_zlxg2">-->
                    <!--<ul></ul>-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="m_zlxg" id="quyu">-->
                <!--<p title="">选择区域</p>-->
                <!--<div class="m_zlxg2">-->
                    <!--<ul></ul>-->
                <!--</div>-->
            <!--</div>-->
            <!--<input id="sfdq_num" type="hidden" value="" />-->
            <!--<input id="csdq_num" type="hidden" value="" />-->
            <!--<input id="sfdq_tj" type="hidden" value="" />-->
            <!--<input id="csdq_tj" type="hidden" value="" />-->
            <!--<input id="qydq_tj" type="hidden" value="" />-->
        <!--</div></li>-->
        <li><span>收货地址</span><textarea style="width:70%;height:100px" type="text"  id="adress">{{ Uinfo.adress }}</textarea></li>
    </ul>
</div>
</div>

<script type="text/javascript" src="js/address.js"></script>
<script type="text/javascript">
// $(function(){
//
// 	$("#area_adr").sjld("#shengfen","#chengshi","#quyu");
//
// });
    function edit_data_ajax(){
        var phone = $('#phone').val()
        var adress = $('#adress').val()
        var csrf = $('input').val()
        layer.confirm('确认要修改联系电话及地址吗？', {
          btn: ['确认','取消'] //按钮
        }, function(){  //确认事件
            var index = layer.load(0, {shade: false});  //加载中图标
            $.post('/index/edit_data_ajax/',{'csrfmiddlewaretoken': csrf,'phone':phone, 'adress':adress},function(data){
                layer.close(index); //停止加载图标
                if(data.res=='1'){
                    layer.alert(data.msg)
                    window.location.href='/index/person';
                    // alert(1);
                }else{
                    layer.alert(data.msg);
                }
            },'json')
        }, function(){
            return
        });

    }
</script>

</body>
</html>

shops_kill-bk/blog/templates/blog/index.html
<!-- saved from url=(0058)https://wqs.jd.com/portal/wx/seckill_m/index.shtml#st=1000 -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
{% load staticfiles %}
    <title>商城秒杀</title>
    <meta name="x5-cache" content="disable">
    <meta name="x-pub" content="">
    <meta name="format-detection" content="telephone=no">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no, viewport-fit=cover">
<meta http-equiv="x-dns-prefetch-control" content="on">


<script type="text/javascript">
function __reloadResource(c){try{var l=document.head||document.getElementsByTagName("head")[0];var b="wq.360buyimg.com";var d=/img\d{1,2}.360buyimg.com/;if(c&&/link/i.test(c.tagName)){if(!c.href||c.href.indexOf(b)==-1){return}var a=document.createElement("link");a.rel="stylesheet";a.href=c.href.replace(b,"wqimg.jd.com");l.appendChild(a)}if(c&&/script/i.test(c.tagName)){if(!c.src||c.src.indexOf(b)==-1){return}var e=document.createElement("script");e.type="text/javascript";e.src=c.src.replace(b,"wqimg.jd.com");l.appendChild(e)}if(c&&/img/i.test(c.tagName)){if(!c.src||!d.test(c.src)){return}c.src=c.src.replace(d,"wqimg.jd.com/imgproxy").replace(".jpg.jpg",".jpg").replace(".png.png",".png")}}catch(e){}};
</script>
    <script>
       window._PFM_TIMING = [[1361, new Date()]];
       window.heatMap = true;
    </script>

    <!-- #include virtual="/sinclude/cssi/fd/h5/wx/seckill/index.shtml" -->
<link combofile="/fd/h5/wx/seckill/index.shtml" rel="stylesheet" href="{% static 'css/index.min_f89eeb50.css' %}" onerror="__reloadResource(this)">


    <script>
        _PFM_TIMING[1] = new Date();
    </script>
<style>img[init-src] { opacity:0; }img[lazyloadimg] { opacity:0; }</style><link rel="stylesheet" type="text/css" charset="utf-8" href="{% static 'css/commonHeader.min.css' %}"></head>
<body>



<script type="text/javascript">
    if(window._unsearch && window.JD){
        JD.sendJs('//wq.360buyimg.com/js/common/dest/wq.unitySearchbar.ea333fcb08.js');
        if(JD.device.scene == "qq"){

        }

        if(JD.device.scene == "weixin" || JD.device.scene == "wxwork"){
        }
    }
</script>
    <div class="qq_menu_layer_v2" style="display:none;z-index:1005" id="__mqqmenu">
</div>





    <header class="jd-header">
    <div class="jd-header-new-title">商城秒杀</div>

    <!-- </div> -->
    </header>
    <!-- </div> -->
    <!-- <style>.seckill_tab{position:sticky;position:-webkit-sticky;}</style> -->
    <div class="wx_wrap J_wrap" vm-container="content">
        <style> .seckill_tab.fixed{position: fixed;top:0}.seckill_tab_jssticky+.seckill_tab_height{height:50px}.seckill_tab_jssticky{top:45px;position: fixed} </style>



        <div class="seckill_tab_height"></div>
        <div> <div class="seckill_items">
            <div class="seckill_items_head"> <h3 class="seckill_items_tit">抢购中 先下单先得哦</h3>
                <!--<div class="seckill_items_timer"> <svg><use xlink:href="#icon_timer"></use></svg>-->
                    <!--<strong>距结束</strong>-->
                    <!--<span>00</span><em>:</em><span>05</span><em>:</em><span>39</span> -->
                <!--</div> -->
            </div>
            <style>.seckill_items_brand .seckill_items_meta:before{display:none}.seckill_items_list>a.bg_stamp{    background-position-x:10%;}</style>
        <div class="seckill_items_list">
        {% for vo in shops %}
        <a href="{% url 'market:detail' vo.id %}" >
            <img class="seckill_items_cover"  src="/upload/{{ vo.pic }}">
            <div class="seckill_items_meta">
                <h4 class="seckill_items_fn">{{ vo.name }}</h4>
                <p class="seckill_items_prices"><span>¥<strong>{{ vo.price }}</strong></span><del>¥{{ vo.oldprice }}</del></p>
                <p class="seckill_items_sq"> <button class="seckill_items_buy">立即抢购</button>
                    <span class="seckill_items_reserve"><strong>已售 {{ vo.percent }}%</strong><span class="seckill_items_reserve_bar"><em style="width: {{ vo.percent }}%;"></em></span></span> </p>
            </div>
        </a>
        {% endfor %}

        <div id="wxloader" style="padding: 50px 0px; background-color: rgb(255, 255, 255); display: none;">
          <div class="wx_loading2"><i class="wx_loading_icon"></i></div>
        </div>


        <div id="J_wxsqTips" class="wxsq_topTips" style="margin: 0px;">
            <p><strong>网站说明</strong>：</p>
            <p>声明：网站为个人网站，仅用作学习，样式主要仿照京东</p>
            <!--<p>划线价：商品展示的划横线价格为参考价，该价格可能是品牌专柜标价、商品吊牌价或  由品牌供应商提供的正品零售价（如厂商指导价、建议零售价等）或该商品在京东平台上曾  经展示过的销售价；由于地区、时间的差异性和市场行情波动，品牌专柜标价、商品吊牌价  等可能会与您购物时展示的不一致，该价格仅供您参考。</p>-->
            <p><strong>小贴士</strong>：积分可以模拟进行购物，新用户注册有5000初始积分，在个人中心可以查看个人积分</p>
            <span id="closeBtmTip" onclick="document.querySelectorAll(&#39;.wxsq_topTips&#39;)[0].style.display=&#39;none&#39;">关闭</span>
        </div>
        <div id="jdappdl"></div>
    </div>


    <div vm-container="common">
        <div class="wx_nav wx_nav_custom">
            <a href="javascript:;" class="on" event_id="MHandSecKill_JDSecKill" event_level="" event_param="">
                <img class="highlight" src="{% static 'img/585b9f36Nab278f9e.png' %}">
                <img class="normal" src="{% static 'img/585b9f36N633d8e72.png' %}"> <span>商城秒杀</span> </a>
            <a href="/index/order_list" class="" event_id="MHandSecKill_BrandTab" event_level="2" event_param="">
                <img class="highlight" src="{% static 'img/59268be5N542317f4.png' %}">
                <img class="normal" src="{% static 'img/59268beaN12f5b721.png' %}"> <span>我的订单</span> </a>
            <a href="/index/person" class="" event_id="MHandSecKill_BrandSecKill" event_level="2" event_param="">
                <img class="highlight" src="{% static 'img/591a6f74N736d1060.png' %}"> <img class="normal" src="{% static 'img/591a6f7cNb11ad011.png' %}"> <span>个人中心</span> </a>

    </div>


<style type="text/css">
.wxsq_topTips {position: relative;padding: 8px 35px 8px 8px;background: #fffad0;font-size: 10px;margin-bottom: 45px;}
.wxsq_topTips span {display: block;width: 40px;height: 40px;line-height: 40px;position: absolute;top: 0;right: 0;color: #3985ff;text-align: center;}
</style>